/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnprocessedTransaction } from '../../models/unprocessed-transaction';

export interface GetUnprocessedTransaction$Params {
    id: string;
}

export function getUnprocessedTransaction(
    http: HttpClient,
    rootUrl: string,
    params: GetUnprocessedTransaction$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<UnprocessedTransaction>> {
    const rb = new RequestBuilder(rootUrl, getUnprocessedTransaction.PATH, 'get');
    if (params) {
        rb.path('id', params.id, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<UnprocessedTransaction>;
            }),
        );
}

getUnprocessedTransaction.PATH = '/v1/unprocessedTransactions/{id}';
