/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnprocessedTransaction } from '../../models/unprocessed-transaction';

export interface GetUnprocessedTransactions$Params {}

export function getUnprocessedTransactions(
    http: HttpClient,
    rootUrl: string,
    params?: GetUnprocessedTransactions$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<UnprocessedTransaction>>> {
    const rb = new RequestBuilder(rootUrl, getUnprocessedTransactions.PATH, 'get');
    if (params) {
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<UnprocessedTransaction>>;
            }),
        );
}

getUnprocessedTransactions.PATH = '/v1/unprocessedTransactions';
