/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BankImporter } from '../../models/bank-importer';
import { BankImporterNoId } from '../../models/bank-importer-no-id';

export interface CreateBankImporter$Params {
    body: BankImporterNoId;
}

export function createBankImporter(
    http: HttpClient,
    rootUrl: string,
    params: CreateBankImporter$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<BankImporter>> {
    const rb = new RequestBuilder(rootUrl, createBankImporter.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<BankImporter>;
            }),
        );
}

createBankImporter.PATH = '/v1/bankImporters';
