/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface DownloadBankImporterFile$Params {
    /**
     * ID of the bank importer file
     */
    id: string;
}

export function downloadBankImporterFile(
    http: HttpClient,
    rootUrl: string,
    params: DownloadBankImporterFile$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Blob>> {
    const rb = new RequestBuilder(rootUrl, downloadBankImporterFile.PATH, 'get');
    if (params) {
        rb.path('id', params.id, {});
    }

    return http
        .request(rb.build({ responseType: 'blob', accept: 'application/octet-stream', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Blob>;
            }),
        );
}

downloadBankImporterFile.PATH = '/v1/bankImporters/files/{id}';
