/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportResult } from '../../models/import-result';

export interface FetchBankImporter$Params {
    /**
     * ID of the bank importer
     */
    id: string;
}

export function fetchBankImporter(
    http: HttpClient,
    rootUrl: string,
    params: FetchBankImporter$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<ImportResult>> {
    const rb = new RequestBuilder(rootUrl, fetchBankImporter.PATH, 'post');
    if (params) {
        rb.path('id', params.id, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<ImportResult>;
            }),
        );
}

fetchBankImporter.PATH = '/v1/bankImporters/{id}/fetch';
