/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Matcher } from '../../models/matcher';
import { MatcherNoId } from '../../models/matcher-no-id';

export interface CreateMatcher$Params {
    body: MatcherNoId;
}

export function createMatcher(
    http: HttpClient,
    rootUrl: string,
    params: CreateMatcher$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Matcher>> {
    const rb = new RequestBuilder(rootUrl, createMatcher.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Matcher>;
            }),
        );
}

createMatcher.PATH = '/v1/matchers';
