/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnalyzeDisbalanceRequest } from '../../models/analyze-disbalance-request';
import { DisbalanceAnalysis } from '../../models/disbalance-analysis';

export interface AnalyzeDisbalance$Params {
    id: string;
    body: AnalyzeDisbalanceRequest;
}

export function analyzeDisbalance(
    http: HttpClient,
    rootUrl: string,
    params: AnalyzeDisbalance$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<DisbalanceAnalysis>> {
    const rb = new RequestBuilder(rootUrl, analyzeDisbalance.PATH, 'post');
    if (params) {
        rb.path('id', params.id, {});
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<DisbalanceAnalysis>;
            }),
        );
}

analyzeDisbalance.PATH = '/v1/accounts/{id}/analyze-disbalance';
