/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnableReconciliationRequest } from '../../models/enable-reconciliation-request';
import { Reconciliation } from '../../models/reconciliation';

export interface EnableAccountReconciliation$Params {
    id: string;
    body: EnableReconciliationRequest;
}

export function enableAccountReconciliation(
    http: HttpClient,
    rootUrl: string,
    params: EnableAccountReconciliation$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Reconciliation>> {
    const rb = new RequestBuilder(rootUrl, enableAccountReconciliation.PATH, 'post');
    if (params) {
        rb.path('id', params.id, {});
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Reconciliation>;
            }),
        );
}

enableAccountReconciliation.PATH = '/v1/accounts/{id}/enable-reconciliation';
