/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Reconciliation } from '../../models/reconciliation';

export interface GetReconciliationHistory$Params {
    id: string;
    currencyId: string;
}

export function getReconciliationHistory(
    http: HttpClient,
    rootUrl: string,
    params: GetReconciliationHistory$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<Reconciliation>>> {
    const rb = new RequestBuilder(rootUrl, getReconciliationHistory.PATH, 'get');
    if (params) {
        rb.path('id', params.id, {});
        rb.query('currencyId', params.currencyId, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<Reconciliation>>;
            }),
        );
}

getReconciliationHistory.PATH = '/v1/accounts/{id}/reconciliation-history';
