/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReconciliationStatus } from '../../models/reconciliation-status';

export interface GetReconciliationStatus$Params {}

export function getReconciliationStatus(
    http: HttpClient,
    rootUrl: string,
    params?: GetReconciliationStatus$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<ReconciliationStatus>>> {
    const rb = new RequestBuilder(rootUrl, getReconciliationStatus.PATH, 'get');
    if (params) {
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<ReconciliationStatus>>;
            }),
        );
}

getReconciliationStatus.PATH = '/v1/reconciliation/status';
