/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MergedTransaction } from '../../models/merged-transaction';

export interface GetMergedTransaction$Params {
    /**
     * Original ID of the transaction that was merged
     */
    id: string;
}

export function getMergedTransaction(
    http: HttpClient,
    rootUrl: string,
    params: GetMergedTransaction$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<MergedTransaction>> {
    const rb = new RequestBuilder(rootUrl, getMergedTransaction.PATH, 'get');
    if (params) {
        rb.path('id', params.id, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<MergedTransaction>;
            }),
        );
}

getMergedTransaction.PATH = '/v1/mergedTransactions/{id}';
