/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MergedTransaction } from '../../models/merged-transaction';

export interface GetMergedTransactions$Params {}

export function getMergedTransactions(
    http: HttpClient,
    rootUrl: string,
    params?: GetMergedTransactions$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<MergedTransaction>>> {
    const rb = new RequestBuilder(rootUrl, getMergedTransactions.PATH, 'get');
    if (params) {
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<MergedTransaction>>;
            }),
        );
}

getMergedTransactions.PATH = '/v1/mergedTransactions';
