/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetItem } from '../../models/budget-item';
import { BudgetItemNoId } from '../../models/budget-item-no-id';

export interface CreateBudgetItem$Params {
    body: BudgetItemNoId;
}

export function createBudgetItem(
    http: HttpClient,
    rootUrl: string,
    params: CreateBudgetItem$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<BudgetItem>> {
    const rb = new RequestBuilder(rootUrl, createBudgetItem.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<BudgetItem>;
            }),
        );
}

createBudgetItem.PATH = '/v1/budgetItems';
