/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetStatus } from '../../models/budget-status';

export interface GetBudgetStatus$Params {
    /**
     * Start date (inclusive)
     */
    from?: string;

    /**
     * End date (exclusive)
     */
    to?: string;

    /**
     * Converts all amounts to this currency
     */
    outputCurrencyId?: string;
}

export function getBudgetStatus(
    http: HttpClient,
    rootUrl: string,
    params?: GetBudgetStatus$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<BudgetStatus>>> {
    const rb = new RequestBuilder(rootUrl, getBudgetStatus.PATH, 'get');
    if (params) {
        rb.query('from', params.from, {});
        rb.query('to', params.to, {});
        rb.query('outputCurrencyId', params.outputCurrencyId, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<BudgetStatus>>;
            }),
        );
}

getBudgetStatus.PATH = '/v1/budgets/status';
