/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetItem } from '../../models/budget-item';

export interface GetBudgetItem$Params {

/**
 * ID of the budgetItem
 */
  id: string;
}

export function getBudgetItem(http: HttpClient, rootUrl: string, params: GetBudgetItem$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetItem>> {
  const rb = new RequestBuilder(rootUrl, getBudgetItem.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetItem>;
    })
  );
}

getBudgetItem.PATH = '/v1/budgetItems/{id}';
