/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccountInfo } from '../models/bank-account-info';
export interface AccountNoId {
    bankInfo?: BankAccountInfo;
    description?: string;
    name: string;

    /**
     * If true, show this account in dashboard summary.
     */
    showInDashboardSummary?: boolean;
    type: 'expense' | 'income' | 'asset';
}
