/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountNoId } from '../models/account-no-id';
import { Entity } from '../models/entity';
export type Account = Entity & AccountNoId & {};
