/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountAggregation {

  /**
   * ID of the account, or name of the tag if groupBy=tag
   */
  accountId: string;
  amounts: Array<number>;
  changePercent?: number;
  total?: number;
}
