/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyAggregation } from '../models/currency-aggregation';
export interface Aggregation {
  currencies: Array<CurrencyAggregation>;
  from: string;
  granularity: 'month' | 'year';
  intervals: Array<string>;
  to: string;
}
