/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLog {
    action: string;
    changeSource: string;
    createdAt: string;
    entityId: string;
    entityType: string;
    id: string;
    snapshot?: string;
    userId: string;
}
