/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLog {
    action: string;
    after?: string | null;
    before?: string | null;
    changeSource: string;
    createdAt: string;
    entityId: string;
    entityType: string;
    id: string;
    userId: string;
}
