/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BankAccountInfo {
    accountId?: string;

    /**
     * List of balances for this account. It's an array since one account could hold multiple currencies, for example, cash account could hold EUR, USD and CZK. Or one bank account could hold multiple currencies.
     */
    balances?: Array<{
        currencyId?: string;
        openingBalance?: number;
        closingBalance?: number;
        lastUpdatedAt?: string | null;
    }>;
    bankId?: string;
}
