/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
export type BankImporterFile = Entity & {
    bankImporterId: string;
    filename: string;
    uploadDate: string;
} & {};
