/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankImporterNoId } from '../models/bank-importer-no-id';
import { Entity } from '../models/entity';
export type BankImporter = Entity & BankImporterNoId & {};
