/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetItemNoId } from '../models/budget-item-no-id';
import { Entity } from '../models/entity';
export type BudgetItem = Entity & BudgetItemNoId & {};
