/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetStatus {
  accountId: string;
  available: number;
  budgeted: number;
  date: string;
  rollover: number;
  spent: number;
}
