/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
export interface ConvertUnprocessedTransaction200Response {
    /**
     * IDs of other unprocessed transactions that were automatically matched because of this conversion (if matcher became perfect)
     */
    autoProcessedIds?: Array<string>;
    transaction: Transaction;
}
