/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountAggregation } from '../models/account-aggregation';
export interface CurrencyAggregation {
  accounts: Array<AccountAggregation>;
  currencyId: string;
}
