/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyNoId } from '../models/currency-no-id';
import { Entity } from '../models/entity';
export type Currency = Entity & CurrencyNoId & {};
