/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DisbalanceCandidateTransaction {
    amount: number;
    date: string;
    description: string;
    id: string;
}
