/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DisbalanceCandidate } from '../models/disbalance-candidate';
export interface DisbalanceAnalysis {
    candidates: Array<DisbalanceCandidate>;
    delta: number;
    transactionCount: number;
}
