/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DisbalanceCandidateTransaction } from '../models/disbalance-candidate-transaction';
export interface DisbalanceCandidate {
    difference: number;
    sum: number;
    transactions: Array<DisbalanceCandidateTransaction>;
    type: 'exact_single' | 'exact_pair' | 'exact_subset' | 'approximate';
}
