/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionNoId } from '../models/transaction-no-id';
export interface MatcherAndTransaction {
  matcherId: string;
  transaction: TransactionNoId;
}
