/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
import { MatcherNoId } from '../models/matcher-no-id';
export type Matcher = Entity & MatcherNoId & {
};

