/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MatcherNoId {
    /**
     * List of booleans representing manual confirmations for this matcher (true = confirmed, false = rejected). Server enforces maximum length configured via application config.
     */
    confirmationHistory?: Array<boolean>;
    currencyRegExp?: string;
    descriptionRegExp?: string;
    extraRegExp?: string;

    /**
     * ID of the matcher image
     */
    image?: string;
    outputAccountId: string;
    outputDescription: string;
    outputTags?: Array<string>;
    partnerAccountNumberRegExp?: string;
    partnerNameRegExp?: string;
}
