/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
export interface MergedTransaction {
    /**
     * When this transaction was merged
     */
    mergedAt: string;
    mergedInto: Transaction;
    transaction: Transaction;
}
