/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
export type Notification = Entity & {
    date: string;
    type: 'other' | 'balanceMatch' | 'balanceDoesntMatch';
    url?: string;
    title: string;
    description: string;
};
