/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Reconciliation {
    accountId: string;
    currencyId: string;
    expectedBalance?: number;
    isManual?: boolean;
    reconciledAt: string;
    reconciledBalance: number;
    reconciliationId?: string;
}
