/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReconciliationNoId {
    accountId: string;
    currencyId: string;
    expectedBalance?: number;
    isManual?: boolean;
    reconciledBalance: number;
}
