/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReconcileAccountRequest {
    /**
     * Manual balance to set. If 0, current Account balance is used.
     */
    balance?: number;
    currencyId: string;
}
