/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReconciliationStatus {
    accountId: string;
    accountName: string;
    appBalance: number;
    bankBalance?: number;
    currencyId: string;
    currencySymbol?: string;
    delta: number;
    hasBankImporter?: boolean;
    hasUnprocessedTransactions?: boolean;
    isManualReconciliationEnabled?: boolean;
    lastReconciledAt?: string | null;
    lastReconciledBalance?: number;
}
