/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
import { TransactionTemplateNoId } from '../models/transaction-template-no-id';
export type TransactionTemplate = Entity & TransactionTemplateNoId & {};
