/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
import { TransactionNoId } from '../models/transaction-no-id';
export type Transaction = Entity & TransactionNoId & {};
