/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionNoId } from '../models/transaction-no-id';
export interface TransactionParseResponse {
    transaction: TransactionNoId;

    /**
     * Human-readable warnings for fields that could not be parsed or were ambiguously matched
     */
    warnings: Array<string>;
}
