/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Movement } from '../models/movement';
export interface TransactionTemplateNoId {
    description?: string;
    extra?: string;
    movements: Array<Movement>;

    /**
     * User-given label for the template
     */
    name: string;
    partnerName?: string;
    place?: string;
    tags?: Array<string>;
}
