/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionParseRequest {
    /**
     * Natural-language transaction description
     */
    text: string;
}
