/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatcherAndTransaction } from '../models/matcher-and-transaction';
import { Transaction } from '../models/transaction';
export interface UnprocessedTransaction {
    duplicates: Array<Transaction>;
    matched: Array<MatcherAndTransaction>;
    transaction: Transaction;
}
