/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Matcher } from '../models/matcher';
export interface UpdateMatcher200Response {
    /**
     * IDs of unprocessed transactions that were automatically matched because of this matcher update
     */
    autoProcessedIds?: Array<string>;
    matcher: Matcher;
}
