/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserPatchBody {
    /**
     * ID of the user's favorite currency. By default this currency will be used to convert other currencies.
     */
    favoriteCurrencyId?: string;
}
