/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entity } from '../models/entity';
export type User = Entity & {
    email: string;
    startDate: string;

    /**
     * ID of the user's favorite currency. By default this currency will be used to convert other currencies.
     */
    favoriteCurrencyId?: string;
};
