/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Account } from '../models/account';
import { BankImporter } from '../models/bank-importer';
import { Currency } from '../models/currency';
import { Matcher } from '../models/matcher';
import { Transaction } from '../models/transaction';
import { User } from '../models/user';
export interface WholeUserData {
    accounts?: Array<Account>;
    bankImporters?: Array<BankImporter>;
    currencies?: Array<Currency>;
    matchers?: Array<Matcher>;
    transactions?: Array<Transaction>;
    user?: User;
}
