/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WholeUserData } from '../../models/whole-user-data';

export interface Export$Params {}

export function export$(
    http: HttpClient,
    rootUrl: string,
    params?: Export$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<WholeUserData>> {
    const rb = new RequestBuilder(rootUrl, export$.PATH, 'post');
    if (params) {
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<WholeUserData>;
            }),
        );
}

export$.PATH = '/v1/export';
