/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionTemplate } from '../../models/transaction-template';

export interface GetTemplates$Params {
    accountId?: string;
}

export function getTemplates(
    http: HttpClient,
    rootUrl: string,
    params?: GetTemplates$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<TransactionTemplate>>> {
    const rb = new RequestBuilder(rootUrl, getTemplates.PATH, 'get');
    if (params) {
        rb.query('accountId', params.accountId, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Array<TransactionTemplate>>;
            }),
        );
}

getTemplates.PATH = '/v1/templates';
