/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Aggregation } from '../../models/aggregation';

export interface GetExpenses$Params {
    /**
     * Uses transactions from this date
     */
    from?: string;

    /**
     * Uses transactions to this date
     */
    to?: string;

    /**
     * Converts all transactions to this currency
     */
    outputCurrencyId?: string;

    /**
     * Granularity of expenses (month or year)
     */
    granularity?: 'month' | 'year';

    /**
     * If true, include hidden accounts
     */
    includeHidden?: boolean;

    /**
     * Field to group results by (account or tag)
     */
    groupBy?: 'account' | 'tag';

    /**
     * Filter by distinct tags
     */
    tags?: Array<string>;

    /**
     * Filter by specific accounts
     */
    accounts?: Array<string>;
}

export function getExpenses(
    http: HttpClient,
    rootUrl: string,
    params?: GetExpenses$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Aggregation>> {
    const rb = new RequestBuilder(rootUrl, getExpenses.PATH, 'get');
    if (params) {
        rb.query('from', params.from, {});
        rb.query('to', params.to, {});
        rb.query('outputCurrencyId', params.outputCurrencyId, {});
        rb.query('granularity', params.granularity, {});
        rb.query('includeHidden', params.includeHidden, {});
        rb.query('groupBy', params.groupBy, {});
        rb.query('tags', params.tags, { style: 'form', explode: true });
        rb.query('accounts', params.accounts, { style: 'form', explode: true });
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Aggregation>;
            }),
        );
}

getExpenses.PATH = '/v1/expenses';
