/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Aggregation } from '../../models/aggregation';

export interface GetIncomes$Params {
    /**
     * Uses transactions from this date
     */
    from?: string;

    /**
     * Uses transactions to this date
     */
    to?: string;

    /**
     * Converts all transactions to this currency
     */
    outputCurrencyId?: string;

    /**
     * If true, include hidden accounts
     */
    includeHidden?: boolean;
}

export function getIncomes(
    http: HttpClient,
    rootUrl: string,
    params?: GetIncomes$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Aggregation>> {
    const rb = new RequestBuilder(rootUrl, getIncomes.PATH, 'get');
    if (params) {
        rb.query('from', params.from, {});
        rb.query('to', params.to, {});
        rb.query('outputCurrencyId', params.outputCurrencyId, {});
        rb.query('includeHidden', params.includeHidden, {});
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Aggregation>;
            }),
        );
}

getIncomes.PATH = '/v1/incomes';
