/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Currency } from '../../models/currency';
import { CurrencyNoId } from '../../models/currency-no-id';

export interface CreateCurrency$Params {
    body: CurrencyNoId;
}

export function createCurrency(
    http: HttpClient,
    rootUrl: string,
    params: CreateCurrency$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Currency>> {
    const rb = new RequestBuilder(rootUrl, createCurrency.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http
        .request(rb.build({ responseType: 'json', accept: 'application/json', context }))
        .pipe(
            filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
            map((r: HttpResponse<any>) => {
                return r as StrictHttpResponse<Currency>;
            }),
        );
}

createCurrency.PATH = '/v1/currencies';
