/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface DeleteAccount$Params {
    /**
     * ID of the account
     */
    id: string;
    /**
     * ID of the account to which transactions should be reassigned
     */
    replaceWithAccountId?: string;
}

export function deleteAccount(
    http: HttpClient,
    rootUrl: string,
    params: DeleteAccount$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
    const rb = new RequestBuilder(rootUrl, deleteAccount.PATH, 'delete');
    if (params) {
        rb.path('id', params.id, {});
        rb.query('replaceWithAccountId', params.replaceWithAccountId, {});
    }

    return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
        }),
    );
}

deleteAccount.PATH = '/v1/accounts/{id}';
