/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountHistory } from '../../models/account-history';

export interface GetAccountHistory$Params {

/**
 * ID of account
 */
  accountId: string;
}

export function getAccountHistory(http: HttpClient, rootUrl: string, params: GetAccountHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountHistory>> {
  const rb = new RequestBuilder(rootUrl, getAccountHistory.PATH, 'get');
  if (params) {
    rb.path('accountId', params.accountId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountHistory>;
    })
  );
}

getAccountHistory.PATH = '/v1/accounts/{accountId}/history';
