/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthData } from '../../models/auth-data';

export interface Authorize$Params {
      body: AuthData
}

export function authorize(http: HttpClient, rootUrl: string, params: Authorize$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token': string;
}>> {
  const rb = new RequestBuilder(rootUrl, authorize.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'token': string;
      }>;
    })
  );
}

authorize.PATH = '/v1/authorize';
